### ISSUE TITLE
Control arrow not show on safari

### ISSUE THREAD

**Issue by cbpi** [lombervid/vueginate#6]
when i open the demo on safari, prev and next svg not show 
![截屏2024-07-23 10 16 51](https://github.com/user-attachments/assets/42618976-259f-432a-a498-d2b5d6c7ec50)

**Comment by lombervid** [comment]
Unfortunately, I don't own an Apple device to test it properly. Could you tell me if you can see them correctly in the second one?: https://codepen.io/lombervid/embed/QWXEOjw

**Comment by cbpi** [comment]
![截屏2024-08-01 16 52 41](https://github.com/user-attachments/assets/19ae9f7f-6885-46eb-b1ce-059f01e1e8dc)

**Comment by lombervid** [comment]
> ![截屏2024-08-01 16 52 41](https://private-user-images.githubusercontent.com/5763573/354155944-19ae9f7f-6885-46eb-b1ce-059f01e1e8dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MjU4MjMsIm5iZiI6MTcyMjUyNTUyMywicGF0aCI6Ii81NzYzNTczLzM1NDE1NTk0NC0xOWFlOWY3Zi02ODg1LTQ2ZWItYjFjZS0wNTlmMDFlMWU4ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMTUxODQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTUyNjgwNGRmZTQ0ZjQ2YzQ3MDNjNmQyMjQwZTE5OGVlMjY4OGMyZWIxZjY4NWNjNzQ2NjlkMTU1YzlmZmZmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZVWB-wGIipqwb-JwYLFwuP_ACcby7prkLVmDaM2Bzco)

Thanks! A patch has already been merged with #9. I'll try to make the release next weekend. 🙂

**Comment by lombervid** [comment]
[New release](https://github.com/lombervid/vueginate/releases/tag/v1.1.2) has been published.
